"""
Super-resolution.

Design choice
-------------
Low-resolution plates (common with distant CCTV cameras) are the case where
learned super-resolution clearly beats classical interpolation, because it
can hallucinate plausible character strokes from learned priors rather than
just smoothing pixels. We use Real-ESRGAN (pretrained, x4) as the default:
it is widely used, has a small/fast "anime/text"-friendly variant, and
requires no fine-tuning to produce a solid baseline.

For higher accuracy, `notebooks/02_finetune_super_resolution.ipynb` fine-tunes
a RRDB/Real-ESRGAN-style generator on *synthetic* low-res/high-res plate
pairs generated by degrading real, clean plate crops (blur + noise +
downsample) -- this sidesteps the fact that paired real LR/HR plate data is
essentially nonexistent, at the cost of a possible synthetic-to-real domain
gap (discussed in the README).

A bicubic fallback keeps the pipeline runnable without GPU/model weights.
"""

from __future__ import annotations

from typing import Optional

import cv2
import numpy as np

import sys
import types

def _patch_basicsr_torchvision_compat():
    """basicsr expects the old torchvision.transforms.functional_tensor
    module, removed in newer torchvision versions. Shim it in before
    basicsr is imported anywhere, so the import doesn't crash."""
    try:
        import torchvision.transforms.functional as F
        functional_tensor = types.ModuleType("torchvision.transforms.functional_tensor")
        functional_tensor.rgb_to_grayscale = F.rgb_to_grayscale
        sys.modules["torchvision.transforms.functional_tensor"] = functional_tensor
    except ImportError:
        pass  # torchvision not installed -- basicsr import will fail anyway

_patch_basicsr_torchvision_compat()


def bicubic_upscale(image: np.ndarray, scale: int = 4) -> np.ndarray:
    h, w = image.shape[:2]
    return cv2.resize(image, (w * scale, h * scale), interpolation=cv2.INTER_CUBIC)


class RealESRGANUpscaler:

    def __init__(self, model_name: str = "RealESRGAN_x4plus", scale: int = 4,
                 weights_path: Optional[str] = "models/super_res/plate_realesrgan_finetuned.pth",
                 tile: int = 0, device: str = "cuda"):
        
        from basicsr.archs.rrdbnet_arch import RRDBNet
        from realesrgan import RealESRGANer

        model = RRDBNet(num_in_ch=3, num_out_ch=3, num_feat=64,
                         num_block=23, num_grow_ch=32, scale=scale)

        self.upsampler = RealESRGANer(
            scale=scale,
            model_path=weights_path,   # None -> realesrgan downloads default weights
            model=model,
            tile=tile,
            tile_pad=10,
            pre_pad=0,
            half=(device == "cuda"),
        )

    def upscale(self, image: np.ndarray, outscale: Optional[int] = None) -> np.ndarray:
        output, _ = self.upsampler.enhance(image, outscale=outscale)
        return output


def super_resolve(
    image: np.ndarray,
    method: str = "real_esrgan",
    scale: int = 4,
    model_name: str = "RealESRGAN_x4plus",
    weights_path: Optional[str] = None,
    tile: int = 0,
    device: str = "cuda",
    _cache: dict = {},
) -> np.ndarray:
    if method == "bicubic":
        return bicubic_upscale(image, scale)

    if method == "real_esrgan":
        key = (model_name, scale, weights_path, tile, device)
        try:
            if key not in _cache:
                _cache[key] = RealESRGANUpscaler(model_name, scale, weights_path, tile, device)
            return _cache[key].upscale(image, outscale=scale)
        except Exception as e:
            print(f"[super_resolve] Real-ESRGAN unavailable ({e}); falling back to bicubic.")
            return bicubic_upscale(image, scale)

    raise ValueError(f"Unknown super-resolution method: {method}")
